project:
  type: website
  output-dir: docs

website:
  title: "Chris Lu's Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About

format:
  html:
    theme: morph
    css: styles.css
    toc: true

editor: visual

